### ISSUE TITLE
Separate repo to the starter solution template?

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/CommonWorkflows#2]
Do we need these to be in a separate repo to the `starter-solution-template`?
If there are workflows a new solution doesn't want, they could readily be deleted after creation from template. 

The use case I can see for an external store is if there are workflows we use only occasionally, but they would be damaging to accidentally include (forget to delete) in a typical new starter solution repo. Do you imagine we will have any such workflows?

**Comment by Greg-Hawkridge** [comment]
This needs to be a separate repo so that the others can refer to it in a central location - via reusable actions
