### ISSUE TITLE
PR workflow failing: Error: Input required and not supplied: github-token

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/CommonWorkflows#5]
The runs of workflow to add prs to tracker are failing on private repos
![image](https://github.com/user-attachments/assets/0ce7a785-f46e-455d-b1ff-3e5b00e25019)
Do private repos need a different token?

On public repos, this run is reported as sucessful and as expected adds the pr to the tracker.

**Comment by Greg-Hawkridge** [comment]
Don't think this is something we can easily fix
